### ISSUE TITLE
Mails werden nicht verschickt mit 1.12

### ISSUE THREAD

**Issue by 37wh5r** [jens-maus/cuxd#10]
Ich habe heute zum ersten Mal RaspberryMatic 2.29.23 und CUxD 1.12 installiert. Beim Senden einer Mail über CUxD enthält das syslog eine Fehlermeldung, die besagt, dass versucht wird auf /etc/config/addons/mh/cloudmatic zuzugreifen:

Dec  6 21:39:36 homematic-raspi daemon.info cuxd[873]: system(/etc/config/addons/mh/cloudmatic 1 ...  exit(127) 0s

Dieses Programm existiert aber nicht!? Es gibt in dem Verzeichnis bei mir nur ein cloudmaticcheck.sh. Wo ist das Executable, oder fehlt vielleicht ein Symbolic Link?

**Comment by uwe111** [comment]
Wahrscheinlich ist auf dem Raspi kein CloudMatic installiert. Per Default sendet der CUxD die Emails per CloudMatic. In der CUxD Doku ist beschrieben, wie man das z.B. auf das Email-Addon umkonfigurieren kann.

**Comment by jens-maus** [comment]
Na klar kommt RaspberryMatic standardmäßig mit CloudMatic ;)

Die Datei bzw. das Verzeichnis `/etc/config/addons/mh/cloudmatic` gibt es übrigens auch nicht auf einer CCU2 mit neueren Firmwares...

**Comment by uwe111** [comment]
auf meiner CCU2 schon:
# ls -l /etc/config/addons/mh/cloudmatic
-rwxrwxrwx    1 root     root          7672 Feb 20  2017 /etc/config/addons/mh/cloudmatic
# cat /boot/VERSION
VERSION=2.29.23

aber auf jeden Fall bleibt ja immer noch die Möglichkeit, es im CUxD-Setup umzukonfigurieren.

**Comment by jens-maus** [comment]
auf meiner nicht: 

```
# ls -l /etc/config/addons/mh/cloudmatic
ls: /etc/config/addons/mh/cloudmatic: No such file or directory
# cat /boot/VERSION
VERSION=2.29.23
```

:) Ich verwende allerdings auch kein CloudMatic auf dieser CCU2. Ggf. wird die Datei ja nur erzeugt wenn man CloudMatic auch eingerichtet/aktiviert hat.

**Comment by 37wh5r** [comment]
Ich hatte alles auf der CCU2 am Laufen, und dachte eigentlich dass bei der Datenübernahme gemäß Anleitung von Herrn Maus auch die CUxD-Settings erhalten bleiben (Email-Addon deinstalliert, CUxD drauf gelassen, Backup gezogen und auf dem Pi eingespielt, und danach CUxD überbügelt mit der RaspberryMatic-Version). Mit Sicherheit habe ich damals die Verwendung des Email-Addons konfiguriert, ich konnte mich nur nicht mehr erinnern. Also einfach in den Geräte-Einstellungen ändern und neu starten. Vielen Dank!

**Comment by 37wh5r** [comment]
Die Beschreibung in der CUxD-Doku ist nur ein Einzeiler mit Absprung zur Email-Addon-Doku, hatte ich übersehen!
