### ISSUE TITLE
CMD_EXEC returns 6

### ISSUE THREAD

**Issue by BT25** [jens-maus/cuxd#12]
Moin,

ich versuche mit CMD_EXEC einen virtuellen Eingang in einem Loxone Miniserver zu schalten.

Im Log steht
system(wget -q -O - 'http://user:password@loxoneIP/dev/sps/io/VI8/Aus') exit(6) 0s 

Was sagt der Errorcode 6? ( exit(6))

**Comment by uwe111** [comment]
Siehe hier: https://gist.github.com/cosimo/5747881
