### ISSUE TITLE
Backupbezeichnung bei RaspberryMatic falsche Version

### ISSUE THREAD

**Issue by Bratmaxe1981** [jens-maus/cuxd#14]
Hallo,
ich nutze zur Zeit RaspberryMatic 3.37.8.20180929.
wenn ich mit CUXD ein Backup meiner Zentrale mit dem Befehl
`/usr/local/addons/cuxd/extra/ccu_backup /mnt/`
erstellen lassen, dann wird dieses wie folgt benannt:
`homematic-ccu2-3.37.8.20180929-2018-10-18-1217.sbk`

Sollte hier nicht ccu_3_ stehen? Ob das bei der echten CCU3 genauso auftritt kann ich nicht sagen.
Ist natürlich nur ein kleiner Schönheitsfehler, wollte es nur melden.

Gruß Carsten

**Comment by jens-maus** [comment]
Änder deinen Hostnamen und schon wird vorne das stehen wie deine CCU im Netzwerk genannt wird.
