### ISSUE TITLE
nanoCUL433 nach Update Raspberrymatic nicht aktiv

### ISSUE THREAD

**Issue by AuelTh** [jens-maus/cuxd#15]
Hallo, jedes mal wenn ich meine Raspberrymatic update muss ich am Schluss den nano Cul kurz am USB ausstecken und wieder stecken, damit er im CuxD erkannt wird. Wie kann man das lösen bzw. kann man am Schluss des Updatevorgangs nicht die USB's nochmal reseten.
Danke

**Comment by uwe111** [comment]
Für CUxD Support nutze bitte das CUxD-Forum: http://cuxd.de
