### ISSUE TITLE
udev rules Symlinks werden ignoriert

### ISSUE THREAD

**Issue by lampi87** [jens-maus/cuxd#18]
Ich habe an meiner Raspberrymatic 2 Sticks hängen. Leider ändert sich die Nummerierung ttyUSB0 bzw 1 fast nach jedem reboot/Update.
Somit habe ich Symlinks mittels udev rules angelegt. Diese funktionieren, das habe ich im Terminal ausprobiert.
Leider kann ich diese aber in cuxd nicht verwenden. Wenn ich statt ttyUSB0 ttyUSBWD verwende (Name des Symlinks) dann steht nur, dass kein tty gerät verbunden ist. Was mache ich falsch?

**Comment by jens-maus** [comment]
Könnte du mal bitte deine udev rules zeigen die du da angelegt hast? Danke.

**Comment by lampi87** [comment]
Ja klar, hier eine der 2 Zeilen:
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", SYMLINK+="ttyUSBWD"

**Comment by lampi87** [comment]
Gibt es Neuigkeiten hierzu?

**Comment by uwe111** [comment]
Um vom CUxD auf verlinkte Devices zugreifen zu können, musst Du sie zuvor im CUxD definieren.
Für CUxD Support nutze bitte das CUxD-Forum: http://cuxd.de
