### ISSUE TITLE
Please log and show charts data with rrdtool

### ISSUE THREAD

**Issue by tuxstef** [jens-maus/cuxd#19]
Hello,
as we have big data it might be much better to use another data storage format than a plain text file with it's low performance.
I suggest to use "rrdtool" instead.
Many well known logging tools including "Cacti" uses this cool stuff.
For details please have a look at https://oss.oetiker.ch/rrdtool/

**Comment by uwe111** [comment]
I suggest that you just convert the plain text files in your prefered format.
That should work with any logging tool then.
