### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by renwin** [jens-maus/cuxd#2]
Command: unzip -o dfu/atmega32u4.zip -d /tmp
Archive:  dfu/atmega32u4.zip
  inflating: CUL_V3_166.hex
  inflating: CUL_V3_ZWAVE_166.hex
  inflating: EUL_USB2TCM.hex

**Comment by jens-maus** [comment]
? What exactly do you want to report here. Please explain rather than just posting some technical output.

**Comment by renwin** [comment]
Wenn ich ein CUL updaten bzw. flashen möchte, kommt dieser Fehler.

**Comment by jens-maus** [comment]
Ich kann da keinen Fehler entdecken. Das ist lediglich die Ausgabe das er die zip datei auspackt.

**Comment by renwin** [comment]
Aber er updatet nicht. Im Internet habe ich gelesen, dass der dfu-programmer ausgetauscht werden müsste. 


Mit freundlichem Gruß R. Wintersberg 
-------- Ursprüngliche Nachricht --------Von: Jens Maus <notifications@github.com> Datum: 05.03.17  10:11  (GMT+01:00) An: jens-maus/cuxd <cuxd@noreply.github.com> Cc: renwin <rene.wintersberg@myownmails.de>, Comment <comment@noreply.github.com> Betreff: Re: [jens-maus/cuxd] Error (#2) 
Ich kann da keinen Fehler entdecken. Das ist lediglich die Ausgabe das er die zip datei auspackt.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jens-maus/cuxd","title":"jens-maus/cuxd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jens-maus/cuxd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jens-maus in #2: Ich kann da keinen Fehler entdecken. Das ist lediglich die Ausgabe das er die zip datei auspackt."}],"action":{"name":"View Issue","url":"https://github.com/jens-maus/cuxd/issues/2#issuecomment-284215284"}}}
