### ISSUE TITLE
CUxD bei CCU3 Upgrade und WeatherCode; single digit issue?

### ISSUE THREAD

**Issue by georgarmbruster** [jens-maus/cuxd#20]
Hallo zusammen,
ich habe folgendes Phänomen, zu dem ich im Netz leider keine Anhaltspunkte gefunden habe. 
Vielleicht habt Ihr eine Idee dazu?

Also: Ich bin von einer CCU2 auf die CCU3 umgestiegen. Backup eingespielt; Zusatzprogramme eingespielt. Alles läuft soweit. Alles, bis auf eine Kleinigkeit  :)

Ich habe einige 433MHz Temperatursensoren angeschlossen. Diese werden vom CUxD auch korrekt erkannt und angeboten. Allerdings kann ich in der CCU-Oberfläche den Weather-Code nicht setzen. Es sieht so aus, als ob hier nur die letzte Ziffer gespeichert wird, nicht aber zwei oder mehr Stellen.

Beispiel: der Weather-Code eines Sensors ist 46, ich gebe 46 ein, speichere, rufe das Gerät neu auf, der Weather Code ist 6. Es wird immer nur die letzte Ziffer gespeichert. 

Ich habe die CCU3 schon zurückgesetzt, auf die akutellste Version upgedated (3.43.15), erst die Software installiert, dann das Backup, CuXD wieder installiert. Das Ergebnis ist das selbe. 

Frage 1: Ist das ein Thema von CUxD oder eher von EQ3? 
Frage 2: Wisst Ihr in welcher Datei die Geräteeigenschaften gespeichert werden? Im Zweifel ist es einfacher, die Weather Codes manuell anzupassen als auf das nächste Update zu warten :)

Erst einmal vielen Dank und schöne Grüße!
Georg

**Comment by uwe111** [comment]
Für CUxD Support nutze bitte das CUxD-Forum: http://cuxd.de
