### ISSUE TITLE
Request for an Universal Device for group of temperatures and states

### ISSUE THREAD

**Issue by heitec11** [jens-maus/cuxd#21]
I had programm an converter to log the data of my central heating system.
At the moment I have only system varaibles with the actual temperatures and states.
Is it possible to have a multiplex device?
Then I can link it also with a room.

**Comment by uwe111** [comment]
Please use the CUxD-Forum for support: http://cuxd.de

**Comment by heitec11** [comment]
Hallo Uwe,
danke. Ich habe es im Forum gefunden.
Ein UWD zeigt nun die Werte meiner Heizung an.
