### ISSUE TITLE
Please secure CUxD by authentication and other changes

### ISSUE THREAD

**Issue by psytester** [jens-maus/cuxd#22]
At least two points should be done to secure the CUxD
1. Please secure the CUxD gateway by forcing an user authentication, if it's called from external and not within a local script.
2. Change the creation of CMD_EXEC Device, that not the default ID ```CUxD.CUX2801001``` is used.
Instead of that well known unique ID on each system a randomized ID should be created.

**Comment by uwe111** [comment]
Please use the CUxD-Forum for support: http://cuxd.de

**Comment by psytester** [comment]
Sorry, I won't register me on an additional forum, just to let you know about security issues.
For details you can contact me.
