### ISSUE TITLE
Installation of CUxD 2.2.0 on CCU3 fails

### ISSUE THREAD

**Issue by muellermartin** [jens-maus/cuxd#23]
Installing CUxD 2.2.0 on a HomeMatic CCU3 with firmware version 3.45.5 fails without further notice. Trying the installation in safe mode did yield the same result. Also resetting it to defaults did not help either. Is there any way to install CUxD on the CCU3 and to find out why the installation failed?

**Comment by uwe111** [comment]
For support please use the CUxD-Forum: http://cuxd.de

**Comment by jens-maus** [comment]
@uwe111 Da du ja die letzten Tickets hier immer recht streng ins forum geleitet hast. soll ich den Issue-Tracker dieses GitHub Projektes abschalten?

**Comment by muellermartin** [comment]
Das könnte man auch einfach in die Projektbschreibung und/oder in die README-Datei schreiben.

**Comment by uwe111** [comment]
@jens-maus Ja, das wäre eine gute Idee. Wo das Forum ja bereits in der Projektbeschreibung erwähnt ist.
