### ISSUE TITLE
Erweiterung des Dateinamens der Backup-Datei um die Firmwareversion des ccu_backup Skripts

### ISSUE THREAD

**Issue by jp112sdl** [jens-maus/cuxd#3]
Ich fände es toll, wenn das Backup-Skript /usr/local/addons/cuxd/extra/ccu_backup im automatisch generierten Dateinamen der Backup-Datei noch die Versions-Nummer einfügt.

So kann man sofort erkennen, unter welche CCU-Firmware das Backup erstellt wurde.
Ich finde es sinnvoll, wenn man mehrere Backup-Generationen aufbewahrt und man mal aufgrund eines Fehlers eine alte CCU-Firmware einspielen muss. Dann geht das Suchen nach dem passenden Backup-File los :) 

Ist nur ein CR 👍 

+`set VERSION [exec sed  -e s/VERSION=//g /boot/VERSION]`
...
-`set BACKUPFILE [set HOSTNAME]-$year-$month-$day-$hour$minute.sbk`
+`set BACKUPFILE [set HOSTNAME]-[set VERSION]-$year-$month-$day-$hour$minute.sbk`

**Comment by jens-maus** [comment]
Dies ist nun in der 1.10 version prinzipiell implementiert.
