### ISSUE TITLE
FeatureRequest: virtueller Drehgriffkontakt, welcher mittels Script gesteuert werden kann

### ISSUE THREAD

**Issue by GasCan1234** [jens-maus/cuxd#4]
Hallo,

ich habe folgende Konstellation bei mir zu Hause eingerichtet:

Je Fenster habe ich zwei Reedkontakte eingebaut um damit die Stellungen geschlossen, gekippt und geöffnet zu erkenn. Diese Kontakte sind an einem Wired-Schlieserkontakt (HMW-Sen-SC-12-DR) angeschlossen und die Zustände werden korrekt im System angezeigt. 

Leider bietet HM nicht die Möglichkeit zwei Kontakte zu einen Drehgriffkontakt zusammen zu fassen. Ich habe es jetzt Beispielhaft für ein Fenster mittels Programm und Systemvariablen gelöst. 
https://homematic-forum.de/forum/viewtopic.php?f=26&t=34811&start=10#p340922

Diese Workaround gefällt mir aber noch nicht so gut und ich würde gern für jedes Fenster ein virtuellen Drehgriffkontakt haben und diesen per Script mit den richtigen Zustand füttern.

Ist dies über CUxD möglich? bzw. könnte man einen solchen Kontakt hinzufügen?

Danke!

**Comment by jp112sdl** [comment]
Da hänge ich mich mal mit dran...
Gute Idee, einen Drehgriff- oder Tristatekontakt könnte ich auch gut gebrauchen!
Ein neuer/weiterer CUxD-Gerätetyp zB (17) HMS100 RHS wäre da sicher toll.

**Comment by uwe111** [comment]
Als CUxD-Gerät (40) Universalsteuerung jetzt möglich!
