### ISSUE TITLE
Webinterface läd nicht

### ISSUE THREAD

**Issue by vr6syncro** [jens-maus/cuxd#8]
https://homematic-forum.de/forum/viewtopic.php?f=37&t=38804&p=382519

Grüße Alex

**Comment by jens-maus** [comment]
Danke für die Info. Inzwischen wurde das Problem lokalisiert und ich habe kurzerhand den 1.11a release erneuert. Also bitte das neue 1.11a Archiv für RaspberryMatic herunterladen und installieren. Nun sollte es gehen.

Siehe https://github.com/jens-maus/cuxd/releases/latest
