### ISSUE TITLE
Feature Request: Anbindung Weishaupt Heizung (WCM-com Modul)

### ISSUE THREAD

**Issue by duffy6** [jens-maus/cuxd#9]
Hallo zusammen,

wäre es möglich eine Anbindung des "WCM-Com Home" Moduls zu ermöglichen?
Dann könnte man die Werte der Heizung auslesen!
Hier gibt es auch den Code (für FHEM):
https://forum.fhem.de/index.php?topic=17718.0

(Ich bin selbst leider kein Coder)

Gruss
Duffy6

**Comment by uwe111** [comment]
Leider gibt es dafür noch keine direkte Anbindung.
Bitte nutze für Support in Zukunft das CUxD-Forum http://cuxd.de, aber da bist Du ja bereits aktiv.
